### ISSUE TITLE
Tests fail when actually requiring node_module dependencies

### ISSUE THREAD

**Issue by KingScooty** [msanand/docker-workflow#4]
Forked the project, and only change i've made is to add `chai` to package.json and require it in the tests file. Tests fail on CircleCI saying `chai` can't be found.

Looks like actually requiring anything from node_modules will fail during the test step.

Made a pull request so you can see what i'm talking about (#5)

**Comment by msanand** [comment]
@KingScooty 
For some reason chai needs to be explicitly installed in the test phase. I've updated pull request #5 to get this working. 
Reference: https://github.com/AngularClass/NG6-starter/issues/48
