### ISSUE TITLE
NodeJS application unable to be deployed on Ubuntu - nodemon issue

### ISSUE THREAD

**Issue by subbu05** [msanand/docker-workflow#8]
npm WARN node@1.0.0 No description
npm WARN node@1.0.0 No repository field.
npm ERR! Linux 3.10.0-327.28.3.el7.x86_64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
# Set the base image to Ubuntu

npm ERR! hiredis@0.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hiredis@0.2.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hiredis package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hiredis
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hiredis
npm ERR! There is likely additional logging output above.

**Comment by msanand** [comment]
@subbu05 I don't see this error. Can you pull the latest and check if this issue is still reproducible?

**Comment by msanand** [comment]
Unable to reproduce issue. Please re-open with more details.
