### ISSUE TITLE
/bin/sh: 1: sudo: not found

### ISSUE THREAD

**Issue by sohale** [msanand/docker-workflow#9]
I receive the following errors

> debconf: unable to initialize frontend: Readline

and then:

> Running hooks in /etc/ca-certificates/update.d...
> done.
> /bin/sh: 1: sudo: not found
> ERROR: Service 'node2' failed to build: The command '/bin/sh -c apt-get update &&     apt-get -y install curl &&     curl -sL https://deb.nodesource.com/setup | sudo bash - &&     apt-get -y install python build-essential nodejs' returned a non-zero code: 127

I use Ubuntu 14.04

**Comment by vesakk** [comment]
Same here

**Comment by thazarik** [comment]
Change node/Dockerfile to use the **14.04.5** image:

> -FROM    ubuntu
> +FROM    ubuntu:trusty
